#!/usr/bin/env python3
"""One place that knows where things live.

Every script imports from here rather than rebuilding paths from `__file__`, so the
repository can be reorganised without hunting through eight files — which is exactly the
reorganisation that created this module.

Layout:

    data/            inputs only: CFD snapshot, study registry, PaintOmics upload bundle
    data/cache/      OSDR + KEGG downloads (git-ignored, regenerated by 00_fetch_osdr.py)
    results/tables/  every derived table, T01… , indexed by MANIFEST.tsv
    results/figures/ every figure, PNG + PDF
    manuscript/      LaTeX
    docs/            the GitHub Pages site
"""

from __future__ import annotations

import os

SCRIPTS = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(SCRIPTS)

DATA = os.path.join(REPO, "data")
CACHE = os.path.join(DATA, "cache")
UPLOAD = os.path.join(DATA, "paintomics_upload")
STUDY_REGISTRY = os.path.join(DATA, "study_registry.tsv")
CFD_SWEEP = os.path.join(DATA, "lunarleaf_gbl_sweep.csv")

RESULTS = os.path.join(REPO, "results")
TABLES = os.path.join(RESULTS, "tables")
FIGURES = os.path.join(RESULTS, "figures")
SUPP_FIGURES = os.path.join(FIGURES, "supplementary")
PAINTOMICS_RAW = os.path.join(RESULTS, "paintomics_raw")

MANUSCRIPT = os.path.join(REPO, "manuscript", "latex")
DOCS = os.path.join(REPO, "docs")
DOCS_DATA = os.path.join(DOCS, "data")
METHODS = os.path.join(REPO, "methods")

# The validated LunarLeaf-CFD checkout this analysis draws its gas transport from.
# Only its results/tables/ are read, and only when a script needs a table that is not
# already vendored under data/. Absent on a fresh clone, which is why every consumer
# falls back to the vendored snapshot.
LUNARLEAF = os.path.expanduser("~/Documents/cose-rollout/LunarLeaf-CFD/results/tables")


def ensure(*dirs: str) -> None:
    """Create output directories on demand."""
    for d in dirs:
        os.makedirs(d, exist_ok=True)


def table(name: str) -> str:
    return os.path.join(TABLES, name)


def figure(name: str) -> str:
    return os.path.join(FIGURES, name)
